# Generated by Django 4.1.1 on 2024-09-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subcontract',
            name='status',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
