# Generated by Django 4.1.1 on 2024-10-19 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.AlterField(
            model_name='contract',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 20, 55, 38, 704007)),
        ),
    ]
