# Generated by Django 4.1.1 on 2024-10-20 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_delete_groups_alter_contract_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 11, 29, 20, 427158, tzinfo=datetime.timezone.utc)),
        ),
    ]
