# Generated by Django 4.1.1 on 2024-09-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_alter_users_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
