# Generated by Django 4.1.1 on 2024-09-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_position_userprofile_subcontract_subcontract_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Function',
        ),
        migrations.AlterField(
            model_name='subcontract',
            name='subcontract_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
