# Generated by Django 4.1.1 on 2024-09-19 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_function',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.function'),
        ),
    ]
