# Generated by Django 4.1.1 on 2024-10-02 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_delete_function_alter_subcontract_subcontract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcontract',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='subcontracts', to='viewer.contract'),
        ),
    ]
