# Generated by Django 4.1.1 on 2024-10-02 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_alter_subcontract_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subcontract', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.subcontract')),
            ],
        ),
    ]
