# Generated by Django 4.1.1 on 2024-10-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_comment'),
        ('viewer', '0007_event'),
    ]

    operations = [
    ]
