# Generated by Django 4.1.1 on 2024-10-05 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('viewer', '0008_merge_0007_comment_0007_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='auth.group'),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Untitled Event', max_length=200),
        ),
    ]
