# Generated by Django 4.1.1 on 2024-10-09 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_contract_deadline_subcontract_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 8, 15, 28, 35, 827308)),
        ),
    ]
