# Generated by Django 4.1.1 on 2024-10-13 15:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0014_securityquestion_userprofile_security_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securityquestion',
            old_name='security_question',
            new_name='question_text',
        ),
        migrations.AlterField(
            model_name='contract',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 17, 24, 44, 258599)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='security_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.securityquestion'),
        ),
    ]
