# Generated by Django 4.2.11 on 2024-10-14 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_rename_security_question_securityquestion_question_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 13, 19, 19, 56, 378731)),
        ),
    ]
