# Generated by Django 4.2.11 on 2024-10-14 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0016_alter_contract_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 13, 19, 20, 24, 602157)),
        ),
    ]
